# Generated by Django 5.1.1 on 2024-10-21 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='category',
            field=models.CharField(default='未分類', max_length=100),
        ),
        migrations.AddField(
            model_name='regulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='regulation',
            index=models.Index(fields=['category'], name='api_regulat_categor_a441bb_idx'),
        ),
        migrations.AddIndex(
            model_name='regulation',
            index=models.Index(fields=['is_active'], name='api_regulat_is_acti_22260b_idx'),
        ),
    ]
