# Generated by Django 5.1.1 on 2024-10-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_regulation_category_regulation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
